GESN_DATA = {
    "short_names": {
		"name": "Наименование и краткая характеристика грунтов",
        "density": "Средняя плотность в естественном залегании кг/м³",
        "work_1": "Механизированная разработка грунтов экскаваторами одноковшовыми",
        "work_2": "Механизированная разработка грунтов экскаваторами траншейными цепными",
        "work_3": "Механизированная разработка грунтов экскаваторами траншейными роторными",
        "work_4": "Механизированная разработка грунтов скреперами",
        "work_5": "Механизированная разработка грунтов бульдозерами",
        "work_6": "Механизированная разработка грунтов грейдерами",
        "work_7": "Механизированная разработка грунтов грейдер-элеваторами",
        "work_8": "Механизированная разработка грунтов бурильнокрановыми машинами",
        "work_9": "Разработка грунтов вручную",
        "work_10": "Разрыхление мерзлых грунтов",
        "work_11": "Нарезка прорезей в мерзлых грунтах баровыми машинами",
        "work_12": "Рыхление грунта бульдозерами рыхлителями",
        "work_13": "Рыхление мерзлых грунтов бульдозерами-рыхлителями"
    },
    "data": {
        "1а": {
            "name": "1а_Алевролиты: а) слабые, низкой прочности",
            "density": 1500,
            "work_1": 4,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 4,
            "work_10": None,
            "work_11": None,
            "work_12": 4,
            "work_13": None
        },
        "1б": {
            "name": "1б_Алевролиты: б) крепкие, малопрочные",
            "density": 2200,
            "work_1": 5,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 5,
            "work_10": None,
            "work_11": None,
            "work_12": 6,
            "work_13": None
        },
        "2": {
            "name": "2_Ангидриты",
            "density": 2900,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 6,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "3а": {
            "name": "3а_Аргиллиты: а) крепкие, плитчатые, малопрочные",
            "density": 2000,
            "work_1": 5,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 5,
            "work_10": None,
            "work_11": None,
            "work_12": 6,
            "work_13": None
        },
        "3б": {
            "name": "3б_Аргиллиты: б) массивные, средней прочности",
            "density": 2200,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 6,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "4": {
            "name": "4_Бокситы плотные, средней прочности",
            "density": 2600,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 6,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "5а": {
            "name": "5а_Вечномерзлые и мерзлые сезонно-протаивающие грунты: а) растительный слой, торф, заторфованные грунты",
            "density": 1150,
            "work_1": 1,
            "work_2": 1,
            "work_3": 1,
            "work_4": 1,
            "work_5": 1,
            "work_6": 1,
            "work_7": None,
            "work_8": None,
            "work_9": 1,
            "work_10": 1,
            "work_11": 1,
            "work_12": None,
            "work_13": 1
        },
        "5б": {
            "name": "5б_Вечномерзлые и мерзлые сезонно-протаивающие грунты: б) пески, супеси, суглинки и глины без примеси",
            "density": 1750,
            "work_1": 2,
            "work_2": 1,
            "work_3": 1,
            "work_4": 1,
            "work_5": 1,
            "work_6": 1,
            "work_7": None,
            "work_8": None,
            "work_9": 1,
            "work_10": 1,
            "work_11": 1,
            "work_12": None,
            "work_13": 1
        },
        "5в": {
            "name": "5в_Вечномерзлые и мерзлые сезонно-протаивающие грунты: в) пески, супеси, суглинки и глины с примесью гравия, гальки, дресвы, щебня в количестве до 20% и валунов до 10%",
            "density": 1950,
            "work_1": 3,
            "work_2": 2,
            "work_3": 2,
            "work_4": 2,
            "work_5": 2,
            "work_6": 2,
            "work_7": None,
            "work_8": None,
            "work_9": 2,
            "work_10": 2,
            "work_11": 2,
            "work_12": None,
            "work_13": 2
        },
        "5г": {
            "name": "5г_Вечномерзлые и мерзлые сезонно-протаивающие грунты: г) пески, супеси, суглинки и глины с примесью гравия, гальки, дресвы, щебня в количестве более 20% и валунов более 10%, а также гравийно-галечные и щебенисто-дресвяные грунты",
            "density": 2100,
            "work_1": 3,
            "work_2": 3,
            "work_3": 3,
            "work_4": 3,
            "work_5": 3,
            "work_6": 3,
            "work_7": None,
            "work_8": None,
            "work_9": 3,
            "work_10": 3,
            "work_11": 3,
            "work_12": None,
            "work_13": 3
        },
        "6а": {
            "name": "6а_Гравийно-галечные грунты (кроме моренных) при размере частиц, мм: а) до 80",
            "density": 1750,
            "work_1": 1,
            "work_2": None,
            "work_3": 2,
            "work_4": 2,
            "work_5": 2,
            "work_6": 3,
            "work_7": None,
            "work_8": None,
            "work_9": 2,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "6б": {
            "name": "6б_Гравийно-галечные грунты (кроме моренных) при размере частиц, мм: б) св. 80",
            "density": 1950,
            "work_1": 2,
            "work_2": None,
            "work_3": 3,
            "work_4": None,
            "work_5": 3,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 3,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "6в": {
            "name": "6в_Гравийно-галечные грунты (кроме моренных) при размере частиц, мм: в) св. 80, с содержанием валунов до 10%",
            "density": 1950,
            "work_1": 3,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": 3,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 3,
            "work_10": None,
            "work_11": None,
            "work_12": 4,
            "work_13": None
        },
        "6г": {
            "name": "6г_Гравийно-галечные грунты (кроме моренных) при размере частиц, мм: г) св. 80, с содержанием валунов до 30%",
            "density": 2000,
            "work_1": 4,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": 4,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 4,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "6д": {
            "name": "6д_Гравийно-галечные грунты (кроме моренных) при размере частиц, мм: д) св. 80, с содержанием валунов до 70%",
            "density": 2300,
            "work_1": 5,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": 4,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 5,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "6е": {
            "name": "6е_Гравийно-галечные грунты (кроме моренных) при размере частиц, мм: е) св. 80, с содержанием валунов св. 70%",
            "density": 2600,
            "work_1": 6,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": 4,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 7,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "6ж": {
            "name": "6ж_Гравийно-галечные грунты (кроме моренных) при размере частиц, мм: ж) цементированная смесь гальки, гравия, мелкозернистого песка и лессовидной супеси",
            "density": "1900-2200",
            "work_1": 4,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 4,
            "work_10": None,
            "work_11": None,
            "work_12": 4,
            "work_13": None
        },
        "7": {
            "name": "7_Гипс",
            "density": 2200,
            "work_1": 5,
            "work_2": None,
            "work_3": 3,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 5,
            "work_10": None,
            "work_11": None,
            "work_12": 6,
            "work_13": None
        },
        "8а": {
            "name": "8а_Глина: а) мягко- и тугопластичная без примесей",
            "density": 1800,
            "work_1": 2,
            "work_2": 3,
            "work_3": 3,
            "work_4": 3,
            "work_5": 3,
            "work_6": 3,
            "work_7": 2,
            "work_8": 1,
            "work_9": 2,
            "work_10": 3,
            "work_11": 2,
            "work_12": None,
            "work_13": 2
        },
        "8б": {
            "name": "8б_Глина: б) мягко- и тугопластичная, с примесью щебня, гальки, гравия или строительного мусора до 10%",
            "density": 1750,
            "work_1": 2,
            "work_2": 3,
            "work_3": 3,
            "work_4": 3,
            "work_5": 3,
            "work_6": 3,
            "work_7": None,
            "work_8": 1,
            "work_9": 2,
            "work_10": 4,
            "work_11": 4,
            "work_12": None,
            "work_13": 3
        },
        "8в": {
            "name": "8в_Глина: в) мягко- и тугопластичная с примесью более 10%",
            "density": 1900,
            "work_1": 3,
            "work_2": None,
            "work_3": 3,
            "work_4": 2,
            "work_5": 2,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 3,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": 3
        },
        "8г": {
            "name": "8г_Глина: г) мягкая карбонная",
            "density": 1950,
            "work_1": 3,
            "work_2": None,
            "work_3": 3,
            "work_4": 2,
            "work_5": 3,
            "work_6": 3,
            "work_7": 3,
            "work_8": 2,
            "work_9": 3,
            "work_10": 4,
            "work_11": 3,
            "work_12": None,
            "work_13": None
        },
        "8д": {
            "name": "8д_Глина: д) твердая карбонная, тяжелая ломовая сланцевая",
            "density": "1950-2150",
            "work_1": 4,
            "work_2": None,
            "work_3": 4,
            "work_4": None,
            "work_5": 3,
            "work_6": None,
            "work_7": None,
            "work_8": 2,
            "work_9": 4,
            "work_10": 4,
            "work_11": 3,
            "work_12": None,
            "work_13": 4
        },
        "9а": {
            "name": "9а_Грунт растительного слоя: а) без корней кустарника и деревьев",
            "density": 1200,
            "work_1": 1,
            "work_2": 1,
            "work_3": 1,
            "work_4": 1,
            "work_5": 1,
            "work_6": 1,
            "work_7": 1,
            "work_8": 1,
            "work_9": 1,
            "work_10": 1,
            "work_11": 1,
            "work_12": None,
            "work_13": 1
        },
        "9б": {
            "name": "9б_Грунт растительного слоя: б) с корнями кустарника и деревьев",
            "density": 1200,
            "work_1": 1,
            "work_2": 2,
            "work_3": 2,
            "work_4": 1,
            "work_5": 2,
            "work_6": None,
            "work_7": None,
            "work_8": 1,
            "work_9": 2,
            "work_10": 1,
            "work_11": 1,
            "work_12": None,
            "work_13": 1
        },
        "9в": {
            "name": "9в_Грунт растительного слоя: в) с примесью щебня, гравия или строительного мусора",
            "density": 1400,
            "work_1": 1,
            "work_2": 2,
            "work_3": 2,
            "work_4": 1,
            "work_5": 2,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 2,
            "work_10": 2,
            "work_11": 3,
            "work_12": None,
            "work_13": 2
        },
        "10а": {
            "name": "10а_Грунты ледникового происхождения (моренные): а) пески, супеси и суглинки при коэффициенте пористости или показателе консистенции более 0,5 и содержании частиц крупнее 2 мм до 10%",
            "density": 1600,
            "work_1": 1,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": 1,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 1,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "10б": {
            "name": "10б_Грунты ледникового происхождения (моренные): б) пески, супеси и суглинки при коэффициенте пористости или показателе консистенции до 0,5; глины при показателе консистенции более 0,5 и содержании частиц крупнее 2 мм до 10%",
            "density": 1800,
            "work_1": 2,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": 2,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 2,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "10в": {
            "name": "10в_Грунты ледникового происхождения (моренные): в) глины при показателе консистенции до 0,5 и содержании частиц крупнее 2 мм до 10%",
            "density": 1850,
            "work_1": 3,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": 3,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 3,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "10г": {
            "name": "10г_Пески, супеси, суглинки и глины при коэффициенте пористости или показателе консистенции более 0,5 и содержании частиц крупнее 2 мм: г) до 35%",
            "density": 1800,
            "work_1": 2,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": 2,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 2,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "10д": {
            "name": "10д_Пески, супеси, суглинки и глины при коэффициенте пористости или показателе консистенции более 0,5 и содержании частиц крупнее 2 мм: д) св. 35 до 65%",
            "density": 1900,
            "work_1": 3,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": 3,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 3,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "10е": {
            "name": "10е_Пески, супеси, суглинки и глины при коэффициенте пористости или показателе консистенции более 0,5 и содержании частиц крупнее 2 мм: е) св. 65%",
            "density": 1950,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": 3,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": None,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "10ж": {
            "name": "10ж_Пески, супеси, суглинки и глины при коэффициенте пористости или показателе консистенции до 0,5 и содержании частиц крупнее 2 мм: ж) до 35%",
            "density": 2000,
            "work_1": 4,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": 3,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 4,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "10з": {
            "name": "10з_Пески, супеси, суглинки и глины при коэффициенте пористости или показателе консистенции до 0,5 и содержании частиц крупнее 2 мм: з) св. 35 до 65%",
            "density": 2100,
            "work_1": 5,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": 4,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 5,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "10и": {
            "name": "10и_Пески, супеси, суглинки и глины при коэффициенте пористости или показателе консистенции до 0,5 и содержании частиц крупнее 2 мм: и) св. 65%",
            "density": 2300,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": 4,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 6,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "10к": {
            "name": "10к_Пески, супеси, суглинки и глины при коэффициенте пористости или показателе консистенции до 0,5 и содержании частиц крупнее 2 мм: к) валунный грунт (содержание частиц крупнее 200 мм более 50%) при любых показателях пористости и консистенции",
            "density": 2500,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": 4,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 7,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "11а": {
            "name": "11а_Диабазы: а) сильно выветрившиеся, малопрочные",
            "density": 2600,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": None,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "11б": {
            "name": "11б_Диабазы: б) слабо выветрившиеся, прочные",
            "density": 2700,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": None,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "11в": {
            "name": "11в_Диабазы: в) не затронутые выветриванием, крепкие, очень прочные",
            "density": 2800,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 7,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "11г": {
            "name": "11г_Диабазы: г) не затронутые выветриванием, особо крепкие, очень прочные",
            "density": 2900,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": None,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "12а": {
            "name": "12а_Доломиты: а) мягкие, пористые, выветрившиеся, средней прочности",
            "density": 2700,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 6,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "12б": {
            "name": "12б_Доломиты: б) плотный, прочный",
            "density": 2800,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 7,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "12в": {
            "name": "12в_Доломиты: в) крепкий, очень прочный",
            "density": 2900,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": None,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "13": {
            "name": "13_Дресва в коренном залегании (элювий)",
            "density": 2000,
            "work_1": 5,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": "5р",
            "work_10": None,
            "work_11": None,
            "work_12": 7,
            "work_13": None
        },
        "14": {
            "name": "14_Дресвяной грунт",
            "density": 1800,
            "work_1": 4,
            "work_2": "",
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": "4р",
            "work_10": None,
            "work_11": None,
            "work_12": 4,
            "work_13": None
        },
        "15а": {
            "name": "15а_Змеевик (серпентин): а) выветрившийся малопрочный",
            "density": 2400,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 5,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "15б": {
            "name": "15б_Змеевик (серпентин): б) средней крепости прочности",
            "density": 2500,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 6,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "15в": {
            "name": "15в_Змеевик (серпентин): в) крепкий, прочный",
            "density": 2600,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 7,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "16а": {
            "name": "16а_Известняки: а) мягкие, пористые, выветрившиеся, малопрочные",
            "density": 1200,
            "work_1": 5,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": "5р",
            "work_10": None,
            "work_11": None,
            "work_12": 5,
            "work_13": None
        },
        "16б": {
            "name": "16б_Известняки: б) мергелистые слабые, средней прочности",
            "density": 2300,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 6,
            "work_10": None,
            "work_11": None,
            "work_12": 6,
            "work_13": None
        },
        "16в": {
            "name": "16в_Известняки: в) мергелистые плотные, прочные",
            "density": 2700,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 7,
            "work_10": None,
            "work_11": None,
            "work_12": 7,
            "work_13": None
        },
        "16г": {
            "name": "16г_Известняки: г) крепкие, доломитизированные, прочные",
            "density": 2900,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": None,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "16д": {
            "name": "16д_Известняки: д) плотные окварцованные, очень прочные",
            "density": 3100,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": None,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "17а": {
            "name": "17а_Кварциты: а) сланцевые, сильно выветрившиеся, средней прочности",
            "density": 2500,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 7,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "17б": {
            "name": "17б_Кварциты: б) сланцевые, средне выветрившиеся, прочные",
            "density": 2600,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": None,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "17в": {
            "name": "17в_Кварциты: в) слабо выветрившиеся, очень прочные",
            "density": 2700,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": None,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "17г": {
            "name": "17г_Кварциты: г) невыветрившиеся, очень прочные",
            "density": 2800,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": None,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "17д": {
            "name": "17д_Кварциты: д) невыветрившиеся, мелкозернистые, очень прочные",
            "density": 3000,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": None,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "18а": {
            "name": "18а_Конгломераты и брекчии: а) слабосцементированные, а также из осадочных пород на глинистом цементе, малопрочные",
            "density": "1900-2100",
            "work_1": 5,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 5,
            "work_10": None,
            "work_11": None,
            "work_12": 6,
            "work_13": None
        },
        "18б": {
            "name": "18б_Конгломераты и брекчии: б) из осадочных пород на известковом цементе, средней прочности",
            "density": 2300,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 6,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "18в": {
            "name": "18в_Конгломераты и брекчии: в) из осадочных пород на кремнистом цементе, прочные",
            "density": 2600,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 7,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "18г": {
            "name": "18г_Конгломераты и брекчии: г) с галькой из изверженных пород на известковом и кремнистом цементе, очень прочные",
            "density": 2900,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": None,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "19а": {
            "name": "19а_Коренные глубинные породы (граниты, гнейсы, диориты, сиениты, габбро и др.): а) крупнозернистые, выветрившиеся и дресвяные, малопрочные",
            "density": 2500,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 5,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "19б": {
            "name": "19б_Коренные глубинные породы (граниты, гнейсы, диориты, сиениты, габбро и др.): б) среднезернистые, выветрившиеся, средней прочности",
            "density": 2600,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 6,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "19в": {
            "name": "19в_Коренные глубинные породы (граниты, гнейсы, диориты, сиениты, габбро и др.): в) мелкозернистые, выветрившиеся, прочные",
            "density": 2700,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 7,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "19г": {
            "name": "19г_Коренные глубинные породы (граниты, гнейсы, диориты, сиениты, габбро и др.): г) крупнозернистые, не затронутые выветриванием, прочные",
            "density": 2800,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": None,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "19д": {
            "name": "19д_Коренные глубинные породы (граниты, гнейсы, диориты, сиениты, габбро и др.): д) среднезернистые, не затронутые выветриванием, очень прочные",
            "density": 2900,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": None,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "19е": {
            "name": "19е_Коренные глубинные породы (граниты, гнейсы, диориты, сиениты, габбро и др.): е) мелкозернистые, не затронутые выветриванием, очень прочные",
            "density": 3100,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": None,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "19ж": {
            "name": "19ж_Коренные глубинные породы (граниты, гнейсы, диориты, сиениты, габбро и др.): ж) микрозернистые, порфировые, не затронутые выветриванием, очень прочные",
            "density": 3300,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": None,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "20а": {
            "name": "20а_Коренные излившиеся породы (андезиты, базальты, порфириты, трахтиты и др.): а) сильно выветрившиеся, средней прочности",
            "density": 2600,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 7,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "20б": {
            "name": "20б_Коренные излившиеся породы (андезиты, базальты, порфириты, трахтиты и др.): б) слабо выветрившиеся, прочные",
            "density": 2700,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": None,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "20в": {
            "name": "20в_Коренные излившиеся породы (андезиты, базальты, порфириты, трахтиты и др.): в) со следами выветривания, очень прочные",
            "density": 2800,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": None,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "20г": {
            "name": "20г_Коренные излившиеся породы (андезиты, базальты, порфириты, трахтиты и др.): г) без следов выветривания, очень прочные",
            "density": 3100,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": None,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "20д": {
            "name": "20д_Коренные излившиеся породы (андезиты, базальты, порфириты, трахтиты и др.): д) не затронутые выветриванием, микроструктурные, очень прочные",
            "density": 3300,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": None,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "21": {
            "name": "21_Кремень очень прочный",
            "density": 3300,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": None,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "22а": {
            "name": "22а_Лесс: а) мягкопластичный",
            "density": 1600,
            "work_1": 1,
            "work_2": 2,
            "work_3": 2,
            "work_4": 1,
            "work_5": 1,
            "work_6": 1,
            "work_7": 1,
            "work_8": 1,
            "work_9": 1,
            "work_10": 2,
            "work_11": 1,
            "work_12": None,
            "work_13": 1
        },
        "22б": {
            "name": "22б_Лесс: б) тугопластичный с примесью гравия или гальки",
            "density": 1800,
            "work_1": 1,
            "work_2": 2,
            "work_3": 2,
            "work_4": 2,
            "work_5": 1,
            "work_6": 2,
            "work_7": None,
            "work_8": None,
            "work_9": 2,
            "work_10": 2,
            "work_11": 1,
            "work_12": None,
            "work_13": None
        },
        "22в": {
            "name": "22в_Лесс: в) твердый",
            "density": 1800,
            "work_1": 4,
            "work_2": 2,
            "work_3": 3,
            "work_4": 2,
            "work_5": 3,
            "work_6": 3,
            "work_7": None,
            "work_8": None,
            "work_9": 3,
            "work_10": 3,
            "work_11": 2,
            "work_12": None,
            "work_13": 2
        },
        "22г": {
            "name": "22г_Лесс: г) рыхлый и слежавшийся",
            "density": 1800,
            "work_1": 2,
            "work_2": 2,
            "work_3": 2,
            "work_4": 2,
            "work_5": 2,
            "work_6": 2,
            "work_7": None,
            "work_8": None,
            "work_9": 2,
            "work_10": 2,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "22д": {
            "name": "22д_Лесс: д) сцементированный",
            "density": 1900,
            "work_1": 3,
            "work_2": 2,
            "work_3": 2,
            "work_4": 2,
            "work_5": 3,
            "work_6": 2,
            "work_7": None,
            "work_8": None,
            "work_9": 3,
            "work_10": 2,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "23а": {
            "name": "23а_Мел: а) мягкий, низкой прочности",
            "density": 1550,
            "work_1": 4,
            "work_2": None,
            "work_3": 4,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 4,
            "work_10": None,
            "work_11": None,
            "work_12": 5,
            "work_13": None
        },
        "23б": {
            "name": "23б_Мел: б) плотный, малопрочный",
            "density": 1800,
            "work_1": 5,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 5,
            "work_10": None,
            "work_11": None,
            "work_12": 6,
            "work_13": None
        },
        "24а": {
            "name": "24а_Мергель: а) мягкий, рыхлый, низкой прочности",
            "density": 1900,
            "work_1": 4,
            "work_2": None,
            "work_3": 4,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 4,
            "work_10": None,
            "work_11": None,
            "work_12": 5,
            "work_13": None
        },
        "24б": {
            "name": "24б_Мергель: б) средний, малопрочный",
            "density": 2300,
            "work_1": 5,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 5,
            "work_10": None,
            "work_11": None,
            "work_12": 6,
            "work_13": None
        },
        "24в": {
            "name": "24в_Мергель: в) плотный средней прочности",
            "density": 2500,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 6,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "25": {
            "name": "25_Мрамор, прочный",
            "density": 2700,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 7,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "26а": {
            "name": "26а_Мусор строительный: а) рыхлый и слежавшийся",
            "density": 1800,
            "work_1": 2,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": 2,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 2,
            "work_10": 2,
            "work_11": None,
            "work_12": None,
            "work_13": 2
        },
        "26б": {
            "name": "26б_Мусор строительный: б) сцементированный",
            "density": 1900,
            "work_1": 3,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": 3,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 3,
            "work_10": 2,
            "work_11": None,
            "work_12": None,
            "work_13": 4
        },
        "27": {
            "name": "27_Опока",
            "density": 1900,
            "work_1": 5,
            "work_2": None,
            "work_3": 4,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 5,
            "work_10": None,
            "work_11": None,
            "work_12": 6,
            "work_13": None
        },
        "28": {
            "name": "28_Пемза",
            "density": 1100,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 5,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "29а": {
            "name": "29а_Песок: а) без примесей",
            "density": 1600,
            "work_1": 1,
            "work_2": 2,
            "work_3": 2,
            "work_4": 2,
            "work_5": 2,
            "work_6": 2,
            "work_7": 3,
            "work_8": 1,
            "work_9": 1,
            "work_10": 2,
            "work_11": 1,
            "work_12": None,
            "work_13": 1
        },
        "29б": {
            "name": "29б_Песок: б) с примесью щебня, гальки, гравия или строительного мусора до 10%",
            "density": 1600,
            "work_1": 1,
            "work_2": 2,
            "work_3": 2,
            "work_4": 2,
            "work_5": 2,
            "work_6": 2,
            "work_7": 3,
            "work_8": 1,
            "work_9": 1,
            "work_10": 2,
            "work_11": 3,
            "work_12": None,
            "work_13": 2
        },
        "29в": {
            "name": "29в_Песок: в) то же, с примесью более 10%",
            "density": 1700,
            "work_1": 1,
            "work_2": None,
            "work_3": 2,
            "work_4": 2,
            "work_5": 2,
            "work_6": 2,
            "work_7": None,
            "work_8": None,
            "work_9": 2,
            "work_10": 2,
            "work_11": 3,
            "work_12": None,
            "work_13": 2
        },
        "29г": {
            "name": "29г_Песок: г) барханный и дюнный",
            "density": 1600,
            "work_1": 2,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": 3,
            "work_6": 3,
            "work_7": None,
            "work_8": None,
            "work_9": 2,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "30а": {
            "name": "30а_Песчаник: а) выветрившийся, малопрочный",
            "density": 2200,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 5,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "30б": {
            "name": "30б_Песчаник: б) на глинистом цементе средней прочности",
            "density": 2300,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 6,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "30в": {
            "name": "30в_Песчаник: в) на известковом цементе, прочный",
            "density": 2500,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 7,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "30г": {
            "name": "30г_Песчаник: г) плотный, на известковом или железистом цементе, прочный",
            "density": 2600,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": None,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "30д": {
            "name": "30д_Песчаник: д) на кварцевом цементе, очень прочный",
            "density": 2700,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": None,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "30е": {
            "name": "30е_Песчаник: е) кремнистый, очень прочный",
            "density": 2700,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": None,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "31а": {
            "name": "31а_Ракушечники: а) слабо цементированные, низкой прочности",
            "density": 1200,
            "work_1": 3,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 4,
            "work_10": None,
            "work_11": None,
            "work_12": 6,
            "work_13": None
        },
        "31б": {
            "name": "31б_Ракушечники: б) сцементированные, малопрочные",
            "density": 1800,
            "work_1": 5,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 5,
            "work_10": None,
            "work_11": None,
            "work_12": 6,
            "work_13": None
        },
        "32": {
            "name": "32_Скальные грунты предварительно разрыхленные (кроме отнесенных к 4 и 5 группам)",
            "density": None,
            "work_1": 6,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": 4,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": None,
            "work_10": None,
            "work_11": None,
            "work_12": 7,
            "work_13": None
        },
        "33а": {
            "name": "33а_Сланцы: а) выветрившиеся, низкой прочности",
            "density": 2000,
            "work_1": 5,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 4,
            "work_10": None,
            "work_11": None,
            "work_12": 6,
            "work_13": None
        },
        "33б": {
            "name": "33б_Сланцы: б) слабо выветрившиеся и глинистые",
            "density": 2600,
            "work_1": 5,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 5,
            "work_10": None,
            "work_11": None,
            "work_12": 7,
            "work_13": None
        },
        "33в": {
            "name": "33в_Сланцы: в) средней прочности",
            "density": 2800,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 6,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "33г": {
            "name": "33г_Сланцы: г) окварцованные, прочные",
            "density": 2300,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 7,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "33д": {
            "name": "33д_Сланцы: д) песчаные, прочные",
            "density": 2500,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": None,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "33е": {
            "name": "33е_Сланцы: е) окремнелые, очень прочные",
            "density": 2600,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": None,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "33ж": {
            "name": "33ж_Сланцы: ж) кремнистые, очень прочные",
            "density": 2600,
            "work_1": None,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": None,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "34а": {
            "name": "34а_Солончаки и солонцы: а) мягкие, пластичные",
            "density": 1600,
            "work_1": 1,
            "work_2": 2,
            "work_3": 2,
            "work_4": 1,
            "work_5": 1,
            "work_6": 1,
            "work_7": 1,
            "work_8": 1,
            "work_9": 2,
            "work_10": 2,
            "work_11": 1,
            "work_12": None,
            "work_13": 2
        },
        "34б": {
            "name": "34б_Солончаки и солонцы: б) твердые",
            "density": 1800,
            "work_1": 3,
            "work_2": 3,
            "work_3": 3,
            "work_4": 3,
            "work_5": 3,
            "work_6": 3,
            "work_7": None,
            "work_8": 2,
            "work_9": 4,
            "work_10": 3,
            "work_11": 2,
            "work_12": 4,
            "work_13": 2
        },
        "35а": {
            "name": "35а_Суглинки: а) легкие и лессовидные, мягкопластичные без примесей",
            "density": 1700,
            "work_1": 1,
            "work_2": 1,
            "work_3": 1,
            "work_4": 1,
            "work_5": 1,
            "work_6": 1,
            "work_7": 1,
            "work_8": 1,
            "work_9": 1,
            "work_10": 2,
            "work_11": 2,
            "work_12": None,
            "work_13": 1
        },
        "35б": {
            "name": "35б_Суглинки: б) то же, с примесью гальки, щебня, гравия или строительного мусора до 10% и тугопластичные без примесей",
            "density": 1700,
            "work_1": 1,
            "work_2": 2,
            "work_3": 2,
            "work_4": 1,
            "work_5": 1,
            "work_6": 1,
            "work_7": None,
            "work_8": 1,
            "work_9": 1,
            "work_10": 3,
            "work_11": 4,
            "work_12": None,
            "work_13": 3
        },
        "35в": {
            "name": "35в_Суглинки: в) легкие и лессовидные, мягкопластичные с примесью гальки, щебня, гравия, или строительного мусора более 10% тугопластичные с примесью до 10%, а также тяжелые, полутвердые и твердые без примесей и с примесью до 10%",
            "density": 1750,
            "work_1": 2,
            "work_2": 3,
            "work_3": 2,
            "work_4": 2,
            "work_5": 2,
            "work_6": 3,
            "work_7": None,
            "work_8": None,
            "work_9": 2,
            "work_10": 3,
            "work_11": 2,
            "work_12": None,
            "work_13": 3
        },
        "35г": {
            "name": "35г_Суглинки: г) тяжелые, полутвердые и твердые с примесью щебня, гальки, гравия или строительного мусора более 10%",
            "density": 1950,
            "work_1": 3,
            "work_2": 3,
            "work_3": 3,
            "work_4": 3,
            "work_5": 2,
            "work_6": 3,
            "work_7": None,
            "work_8": None,
            "work_9": 3,
            "work_10": 3,
            "work_11": 4,
            "work_12": None,
            "work_13": 4
        },
        "36а": {
            "name": "36а_Супеси: а) легкие, пластичные без примесей",
            "density": 1650,
            "work_1": 1,
            "work_2": 2,
            "work_3": 2,
            "work_4": 2,
            "work_5": 2,
            "work_6": 2,
            "work_7": 2,
            "work_8": 2,
            "work_9": 1,
            "work_10": 1,
            "work_11": 1,
            "work_12": None,
            "work_13": 1
        },
        "36б": {
            "name": "36б_Супеси: б) твердые без примесей, а также пластичные и твердые с примесью щебня, гальки, гравия или строительного мусора до 10%",
            "density": 1650,
            "work_1": 1,
            "work_2": 2,
            "work_3": 2,
            "work_4": 2,
            "work_5": 2,
            "work_6": 2,
            "work_7": 2,
            "work_8": 2,
            "work_9": 1,
            "work_10": 2,
            "work_11": 3,
            "work_12": None,
            "work_13": 2
        },
        "36в": {
            "name": "36в_Супеси: в) то же, с примесью до 30%",
            "density": 1800,
            "work_1": 1,
            "work_2": 2,
            "work_3": 2,
            "work_4": 2,
            "work_5": 2,
            "work_6": 2,
            "work_7": None,
            "work_8": None,
            "work_9": 2,
            "work_10": 2,
            "work_11": 3,
            "work_12": None,
            "work_13": 2
        },
        "36г": {
            "name": "36г_Супеси: г) то же, с примесью более 30%",
            "density": 1850,
            "work_1": 1,
            "work_2": 2,
            "work_3": 2,
            "work_4": 2,
            "work_5": 2,
            "work_6": 2,
            "work_7": None,
            "work_8": None,
            "work_9": 3,
            "work_10": 2,
            "work_11": 3,
            "work_12": None,
            "work_13": 2
        },
        "37а": {
            "name": "37а_Торф: а) без древесных корней",
            "density": "800-1000",
            "work_1": 1,
            "work_2": 1,
            "work_3": 1,
            "work_4": 1,
            "work_5": 1,
            "work_6": 1,
            "work_7": 1,
            "work_8": 1,
            "work_9": 1,
            "work_10": 2,
            "work_11": 1,
            "work_12": None,
            "work_13": 1
        },
        "37б": {
            "name": "37б_Торф: б) с древесными корнями толщиной до 30 мм",
            "density": "850-1050",
            "work_1": 1,
            "work_2": 1,
            "work_3": 1,
            "work_4": 2,
            "work_5": 2,
            "work_6": 2,
            "work_7": None,
            "work_8": 1,
            "work_9": 2,
            "work_10": 2,
            "work_11": 2,
            "work_12": None,
            "work_13": 2
        },
        "37в": {
            "name": "37в_Торф: в) то же, более 30 мм",
            "density": "900-1200",
            "work_1": 2,
            "work_2": 2,
            "work_3": 2,
            "work_4": 2,
            "work_5": 2,
            "work_6": 2,
            "work_7": None,
            "work_8": None,
            "work_9": 2,
            "work_10": 2,
            "work_11": 2,
            "work_12": None,
            "work_13": 2
        },
        "38а": {
            "name": "38а_Трепел: а) слабый, низкой прочности",
            "density": 1500,
            "work_1": 4,
            "work_2": None,
            "work_3": 4,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 4,
            "work_10": None,
            "work_11": None,
            "work_12": 5,
            "work_13": None
        },
        "38б": {
            "name": "38б_Трепел: б) плотный, малопрочный",
            "density": 1770,
            "work_1": 5,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 5,
            "work_10": None,
            "work_11": None,
            "work_12": 6,
            "work_13": None
        },
        "39": {
            "name": "39_Туф",
            "density": 1100,
            "work_1": 5,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": None,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 5,
            "work_10": None,
            "work_11": None,
            "work_12": 6,
            "work_13": None
        },
        "40а": {
            "name": "40а_Черноземы и каштановые грунты: а) мягкие, пластичные",
            "density": 1300,
            "work_1": 1,
            "work_2": 1,
            "work_3": 1,
            "work_4": 1,
            "work_5": 1,
            "work_6": 1,
            "work_7": 2,
            "work_8": 1,
            "work_9": 1,
            "work_10": 2,
            "work_11": 2,
            "work_12": None,
            "work_13": 2
        },
        "40б": {
            "name": "40б_Черноземы и каштановые грунты: б) то же, с корнями кустарника и деревьев",
            "density": 1300,
            "work_1": 1,
            "work_2": 1,
            "work_3": 1,
            "work_4": 1,
            "work_5": 1,
            "work_6": 1,
            "work_7": 2,
            "work_8": 1,
            "work_9": 2,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": 2
        },
        "40в": {
            "name": "40в_Черноземы и каштановые грунты: в) твердые",
            "density": 1200,
            "work_1": 2,
            "work_2": 2,
            "work_3": 2,
            "work_4": 2,
            "work_5": 2,
            "work_6": 3,
            "work_7": 3,
            "work_8": 2,
            "work_9": 3,
            "work_10": 2,
            "work_11": 2,
            "work_12": None,
            "work_13": 2
        },
        "41а": {
            "name": "41а_Щебень: а) при размере частиц до 40 мм",
            "density": 1750,
            "work_1": 2,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": 3,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 2,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "41б": {
            "name": "41б_Щебень: б) при размере частиц до 150 мм",
            "density": 1950,
            "work_1": 2,
            "work_2": None,
            "work_3": None,
            "work_4": None,
            "work_5": 3,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 3,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "42а": {
            "name": "42а_Шлаки: а) котельные, рыхлые",
            "density": 700,
            "work_1": 1,
            "work_2": 1,
            "work_3": 1,
            "work_4": None,
            "work_5": 1,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 1,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "42б": {
            "name": "42б_Шлаки: б) котельные, слежавшиеся",
            "density": 700,
            "work_1": 1,
            "work_2": 1,
            "work_3": 1,
            "work_4": None,
            "work_5": 1,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 2,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "42в": {
            "name": "42в_Шлаки: в) металлургические выветрившиеся",
            "density": None,
            "work_1": 2,
            "work_2": 2,
            "work_3": 2,
            "work_4": None,
            "work_5": 1,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 3,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        },
        "42г": {
            "name": "42г_Шлаки: г) металлургические невыветрившиеся",
            "density": 1500,
            "work_1": 3,
            "work_2": None,
            "work_3": 2,
            "work_4": None,
            "work_5": 3,
            "work_6": None,
            "work_7": None,
            "work_8": None,
            "work_9": 4,
            "work_10": None,
            "work_11": None,
            "work_12": None,
            "work_13": None
        }
    }
}